#include "InventoryController.h"
#include "../plugins/InventoryService.h"
#include "../AuditLog.h"
using namespace drogon;
namespace {HttpResponsePtr out(Json::Value j,HttpStatusCode c=k200OK){auto r=HttpResponse::newHttpJsonResponse(j);r->setStatusCode(c);return r;}HttpResponsePtr err(std::string s,HttpStatusCode c=k400BadRequest){Json::Value j;j["error"]=s;return out(j,c);}bool manager(const HttpRequestPtr&r){try{return r->attributes()->get<std::string>("role")=="manager";}catch(...){return false;}}}
Task<HttpResponsePtr> InventoryController::items(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto v=co_await app().getPlugin<InventoryService>()->items();Json::Value a(Json::arrayValue);for(auto&i:v){Json::Value j;j["id"]=i.id;j["name"]=i.name;j["unit"]=i.unit;j["is_active"]=i.is_active;j["on_hand"]=i.on_hand;a.append(j);}co_return out(a);}
Task<HttpResponsePtr> InventoryController::createItem(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();if(!j)co_return err("Invalid JSON");try{auto id=co_await app().getPlugin<InventoryService>()->createItem((*j)["name"].asString(),(*j)["unit"].asString());Json::Value x;x["id"]=id;co_return out(x,k201Created);}catch(std::exception&e){co_return err(e.what());}}
Task<HttpResponsePtr> InventoryController::updateItem(HttpRequestPtr r,int64_t id){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();if(!j)co_return err("Invalid JSON");try{Json::Value before;for(auto&i:co_await app().getPlugin<InventoryService>()->items())if(i.id==id){before["name"]=i.name;before["unit"]=i.unit;before["is_active"]=i.is_active;}bool ok=co_await app().getPlugin<InventoryService>()->updateItem(id,(*j)["name"].asString(),(*j)["unit"].asString(),j->get("is_active",true).asBool());Json::Value x;x["success"]=ok;if(ok)writeChangeAudit(r,"SỬA NGUYÊN LIỆU","inventory_item#"+std::to_string(id),before,*j,{"name","unit","is_active"});co_return out(x,ok?k200OK:k404NotFound);}catch(std::exception&e){co_return err(e.what());}}
Task<HttpResponsePtr> InventoryController::lots(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto v=co_await app().getPlugin<InventoryService>()->lots();Json::Value a(Json::arrayValue);for(auto&i:v){Json::Value j;j["id"]=i.id;j["item_id"]=i.item_id;j["item_name"]=i.item_name;j["quantity"]=i.quantity;j["remaining"]=i.remaining;j["unit_cost"]=i.unit_cost;j["purchased_at"]=i.purchased_at;j["expires_at"]=i.expires_at;j["is_void"]=i.is_void;a.append(j);}co_return out(a);}
Task<HttpResponsePtr> InventoryController::createLot(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();if(!j)co_return err("Invalid JSON");try{auto id=co_await app().getPlugin<InventoryService>()->createLot((*j)["item_id"].asInt64(),(*j)["quantity"].asDouble(),(*j)["unit_cost"].asInt64(),(*j)["purchased_at"].asInt64(),(*j)["expires_at"].asInt64(),j->get("note","").asString());Json::Value x;x["id"]=id;co_return out(x,k201Created);}catch(std::exception&e){co_return err(e.what());}}
Task<HttpResponsePtr> InventoryController::voidLot(HttpRequestPtr r,int64_t id){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();Json::Value before;for(auto&i:co_await app().getPlugin<InventoryService>()->lots())if(i.id==id){before["quantity"]=i.quantity;before["unit_cost"]=i.unit_cost;before["purchased_at"]=i.purchased_at;before["expires_at"]=i.expires_at;before["is_void"]=i.is_void;}bool ok=co_await app().getPlugin<InventoryService>()->voidLot(id,j?j->get("note","voided by manager").asString():"voided by manager");Json::Value x;x["success"]=ok;if(ok){Json::Value after=before;after["is_void"]=true;writeChangeAudit(r,"HỦY LÔ KHO","inventory_lot#"+std::to_string(id),before,after,{"quantity","unit_cost","purchased_at","expires_at","is_void"});}co_return out(x,ok?k200OK:k404NotFound);}
Task<HttpResponsePtr> InventoryController::recipes(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);std::optional<int64_t>p;if(!r->getParameter("product_id").empty())p=std::stoll(r->getParameter("product_id"));auto v=co_await app().getPlugin<InventoryService>()->recipes(p);Json::Value a(Json::arrayValue);for(auto&i:v){Json::Value j;j["id"]=i.id;j["product_id"]=i.product_id;j["item_id"]=i.item_id;j["item_name"]=i.item_name;j["unit"]=i.unit;j["quantity"]=i.quantity;j["is_active"]=i.is_active;a.append(j);}co_return out(a);}
Task<HttpResponsePtr> InventoryController::createRecipe(HttpRequestPtr r){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();if(!j)co_return err("Invalid JSON");try{auto id=co_await app().getPlugin<InventoryService>()->createRecipe((*j)["product_id"].asInt64(),(*j)["item_id"].asInt64(),(*j)["quantity"].asDouble());Json::Value x;x["id"]=id;co_return out(x,k201Created);}catch(std::exception&e){co_return err(e.what());}}
Task<HttpResponsePtr> InventoryController::updateRecipe(HttpRequestPtr r,int64_t id){if(!manager(r))co_return err("Permission denied",k403Forbidden);auto j=r->getJsonObject();if(!j)co_return err("Invalid JSON");try{Json::Value before;for(auto&i:co_await app().getPlugin<InventoryService>()->recipes(std::nullopt))if(i.id==id){before["quantity"]=i.quantity;before["is_active"]=i.is_active;}bool ok=co_await app().getPlugin<InventoryService>()->updateRecipe(id,(*j)["quantity"].asDouble(),j->get("is_active",true).asBool());Json::Value x;x["success"]=ok;if(ok)writeChangeAudit(r,"SỬA CÔNG THỨC","recipe#"+std::to_string(id),before,*j,{"quantity","is_active"});co_return out(x,ok?k200OK:k404NotFound);}catch(std::exception&e){co_return err(e.what());}}
