#include "InventoryRepo.h"
#include <ctime>
#include <map>
using namespace drogon; using namespace drogon::orm;
DbClientPtr InventoryRepo::db() const { return app().getDbClient(); }
void InventoryRepo::init_db(){ auto c=db();
c->execSqlSync("CREATE TABLE IF NOT EXISTS inventory_items(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,unit TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN(0,1)),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
c->execSqlSync("CREATE TABLE IF NOT EXISTS inventory_lots(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,quantity REAL NOT NULL CHECK(quantity>0),unit_cost INTEGER NOT NULL CHECK(unit_cost>=0),purchased_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL,is_void INTEGER NOT NULL DEFAULT 0 CHECK(is_void IN(0,1)),note TEXT NOT NULL DEFAULT '',FOREIGN KEY(item_id) REFERENCES inventory_items(id))");
c->execSqlSync("CREATE TABLE IF NOT EXISTS product_inventory_links(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,item_id INTEGER NOT NULL,quantity REAL NOT NULL CHECK(quantity>0),is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN(0,1)),created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(product_id,item_id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(item_id) REFERENCES inventory_items(id))");
c->execSqlSync("CREATE TABLE IF NOT EXISTS inventory_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,lot_id INTEGER,quantity_delta REAL NOT NULL,kind TEXT NOT NULL,reference_type TEXT,reference_id INTEGER,note TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,FOREIGN KEY(item_id) REFERENCES inventory_items(id),FOREIGN KEY(lot_id) REFERENCES inventory_lots(id))");
c->execSqlSync("CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_order_consumption ON inventory_movements(reference_type,reference_id,item_id) WHERE reference_type='order' AND kind='sale'");
}
Task<int64_t> InventoryRepo::createItem(const std::string& n,const std::string& u){auto t=(int64_t)time(nullptr);auto r=co_await db()->execSqlCoro("INSERT INTO inventory_items(name,unit,created_at,updated_at) VALUES(?,?,?,?)",n,u,t,t);co_return r.insertId();}
Task<bool> InventoryRepo::updateItem(int64_t id,const std::string& n,const std::string& u,bool a){auto r=co_await db()->execSqlCoro("UPDATE inventory_items SET name=?,unit=?,is_active=?,updated_at=? WHERE id=?",n,u,a?1:0,(int64_t)time(nullptr),id);co_return r.affectedRows()>0;}
Task<std::vector<InventoryItem>> InventoryRepo::listItems(int limit,int offset,bool activeOnly){std::string s="SELECT i.id,i.name,i.unit,i.is_active,i.created_at,i.updated_at,COALESCE(SUM(m.quantity_delta),0) on_hand FROM inventory_items i LEFT JOIN inventory_movements m ON m.item_id=i.id";if(activeOnly)s+=" WHERE i.is_active=1";s+=" GROUP BY i.id ORDER BY i.name LIMIT ? OFFSET ?";auto r=co_await db()->execSqlCoro(s,limit,offset);std::vector<InventoryItem> v;for(auto x:r)v.push_back({x["id"].as<int64_t>(),x["name"].as<std::string>(),x["unit"].as<std::string>(),x["is_active"].as<int>()==1,x["created_at"].as<int64_t>(),x["updated_at"].as<int64_t>(),x["on_hand"].as<double>()});co_return v;}
Task<int64_t> InventoryRepo::createLot(int64_t item,double q,int64_t cost,int64_t bought,int64_t expiry,const std::string& note){auto c=db();auto t=(int64_t)time(nullptr);auto r=co_await c->execSqlCoro("INSERT INTO inventory_lots(item_id,quantity,unit_cost,purchased_at,expires_at,created_at,note) VALUES(?,?,?,?,?,?,?)",item,q,cost,bought,expiry,t,note);auto id=r.insertId();co_await c->execSqlCoro("INSERT INTO inventory_movements(item_id,lot_id,quantity_delta,kind,reference_type,reference_id,note,created_at) VALUES(?,?,?,'purchase','lot',?,?,?)",item,id,q,id,note,t);co_return id;}
Task<bool> InventoryRepo::voidLot(int64_t id,const std::string& note){auto c=db();auto rows=co_await c->execSqlCoro("SELECT item_id,quantity,is_void FROM inventory_lots WHERE id=?",id);if(rows.empty()||rows[0]["is_void"].as<int>())co_return false;auto item=rows[0]["item_id"].as<int64_t>();auto q=rows[0]["quantity"].as<double>();co_await c->execSqlCoro("UPDATE inventory_lots SET is_void=1 WHERE id=?",id);co_await c->execSqlCoro("INSERT INTO inventory_movements(item_id,lot_id,quantity_delta,kind,reference_type,reference_id,note,created_at) VALUES(?,?,?,'void_purchase','lot',?,?,?)",item,id,-q,id,note,(int64_t)time(nullptr));co_return true;}
Task<std::vector<InventoryLot>> InventoryRepo::listLots(int limit,int offset,std::optional<int64_t> from,std::optional<int64_t> to){std::string s="SELECT l.id,l.item_id,i.name item_name,l.quantity,l.unit_cost,l.purchased_at,l.expires_at,l.created_at,l.is_void,l.quantity+COALESCE((SELECT SUM(m.quantity_delta) FROM inventory_movements m WHERE m.lot_id=l.id AND m.kind<>'purchase'),0) remaining FROM inventory_lots l JOIN inventory_items i ON i.id=l.item_id WHERE 1=1";if(from)s+=" AND l.purchased_at>="+std::to_string(*from);if(to)s+=" AND l.purchased_at<="+std::to_string(*to);s+=" ORDER BY l.purchased_at DESC,l.id DESC LIMIT ? OFFSET ?";auto r=co_await db()->execSqlCoro(s,limit,offset);std::vector<InventoryLot> v;for(auto x:r)v.push_back({x["id"].as<int64_t>(),x["item_id"].as<int64_t>(),x["item_name"].as<std::string>(),x["quantity"].as<double>(),x["remaining"].as<double>(),x["unit_cost"].as<int64_t>(),x["purchased_at"].as<int64_t>(),x["expires_at"].as<int64_t>(),x["created_at"].as<int64_t>(),x["is_void"].as<int>()==1});co_return v;}
Task<int64_t> InventoryRepo::createRecipe(int64_t p,int64_t i,double q){auto t=(int64_t)time(nullptr);auto r=co_await db()->execSqlCoro("INSERT INTO product_inventory_links(product_id,item_id,quantity,created_at,updated_at) VALUES(?,?,?,?,?)",p,i,q,t,t);co_return r.insertId();}
Task<bool> InventoryRepo::updateRecipe(int64_t id,double q,bool a){auto r=co_await db()->execSqlCoro("UPDATE product_inventory_links SET quantity=?,is_active=?,updated_at=? WHERE id=?",q,a?1:0,(int64_t)time(nullptr),id);co_return r.affectedRows()>0;}
Task<std::vector<RecipeLink>> InventoryRepo::listRecipes(std::optional<int64_t> p,int limit,int offset,bool activeOnly){std::string s="SELECT l.id,l.product_id,l.item_id,i.name item_name,i.unit,l.quantity,l.is_active FROM product_inventory_links l JOIN inventory_items i ON i.id=l.item_id WHERE 1=1";if(p)s+=" AND l.product_id="+std::to_string(*p);if(activeOnly)s+=" AND l.is_active=1";s+=" ORDER BY l.product_id,i.name LIMIT ? OFFSET ?";auto r=co_await db()->execSqlCoro(s,limit,offset);std::vector<RecipeLink> v;for(auto x:r)v.push_back({x["id"].as<int64_t>(),x["product_id"].as<int64_t>(),x["item_id"].as<int64_t>(),x["item_name"].as<std::string>(),x["unit"].as<std::string>(),x["quantity"].as<double>(),x["is_active"].as<int>()==1});co_return v;}
Task<std::vector<InventoryMovement>> InventoryRepo::listMovements(int limit,int offset,std::optional<int64_t> from,std::optional<int64_t> to,const std::optional<std::string>& kind){std::string s="SELECT m.id,m.item_id,i.name item_name,i.unit,m.lot_id,m.quantity_delta,m.kind,m.reference_type,m.reference_id,m.note,m.created_at FROM inventory_movements m JOIN inventory_items i ON i.id=m.item_id WHERE 1=1";if(from)s+=" AND m.created_at>="+std::to_string(*from);if(to)s+=" AND m.created_at<="+std::to_string(*to);if(kind)s+=" AND m.kind='"+*kind+"'";s+=" ORDER BY m.created_at DESC,m.id DESC LIMIT ? OFFSET ?";auto r=co_await db()->execSqlCoro(s,limit,offset);std::vector<InventoryMovement> v;for(auto x:r){InventoryMovement m;m.id=x["id"].as<int64_t>();m.item_id=x["item_id"].as<int64_t>();m.item_name=x["item_name"].as<std::string>();m.unit=x["unit"].as<std::string>();if(!x["lot_id"].isNull())m.lot_id=x["lot_id"].as<int64_t>();m.quantity_delta=x["quantity_delta"].as<double>();m.kind=x["kind"].as<std::string>();m.reference_type=x["reference_type"].isNull()?"":x["reference_type"].as<std::string>();if(!x["reference_id"].isNull())m.reference_id=x["reference_id"].as<int64_t>();m.note=x["note"].as<std::string>();m.created_at=x["created_at"].as<int64_t>();v.push_back(std::move(m));}co_return v;}
Task<void> InventoryRepo::consumeOrder(int64_t order,const std::vector<std::pair<int64_t,int>>& items){auto c=db();auto t=(int64_t)time(nullptr);std::map<int64_t,double> desired;for(auto [p,count]:items){auto rs=co_await c->execSqlCoro("SELECT item_id,quantity FROM product_inventory_links WHERE product_id=? AND is_active=1",p);for(auto x:rs)desired[x["item_id"].as<int64_t>()]-=x["quantity"].as<double>()*count;}auto old=co_await c->execSqlCoro("SELECT item_id,SUM(quantity_delta) total FROM inventory_movements WHERE reference_type='order' AND reference_id=? GROUP BY item_id",order);std::map<int64_t,double> current;for(auto x:old)current[x["item_id"].as<int64_t>()]=x["total"].as<double>();for(auto [iid,cur]:current)if(!desired.count(iid))desired[iid]=0;for(auto [iid,want]:desired){double delta=want-current[iid];if(delta!=0)co_await c->execSqlCoro("INSERT INTO inventory_movements(item_id,quantity_delta,kind,reference_type,reference_id,note,created_at) VALUES(?,?,'sale_adjustment','order',?,'order synchronized',?)",iid,delta,order,t);}co_return;}
